name: .NET Pipeline (Conditional)

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies (skip if no .csproj or .sln)
        run: |
          if ls **/*.csproj **/*.sln 1> /dev/null 2>&1; then
            echo "Project/solution file found. Running restore..."
            dotnet restore
          else
            echo "No .csproj or .sln file found. Skipping restore."
          fi

      - name: Build (skip if no .csproj or .sln)
        run: |
          if ls **/*.csproj **/*.sln 1> /dev/null 2>&1; then
            echo "Project/solution file found. Running build..."
            dotnet build --configuration Release
          else
            echo "No .csproj or .sln file found. Skipping build."
          fi

      - name: Test (skip if no .csproj or .sln)
        run: |
          if ls **/*.csproj **/*.sln 1> /dev/null 2>&1; then
            echo "Project/solution file found. Running tests..."
            dotnet test --no-build --verbosity normal
          else
            echo "No .csproj or .sln file found. Skipping tests."
          fi
